/**
 * Please dont change this file. If you want change it, you must update deeplink for Front-end/Back-end
 */
export enum LMMTabConfiguration {
  CoursesTab = 'courses',
  PendingApprovalTab = 'pending-approval',
  CourseInfoTab = 'course-info',
  FeedbackTab = 'feedback',
  ClassRunsTab = 'classruns',
  SessionsTab = 'sessions',
  CourseContentTab = 'course-content',
  AllClassRunsTab = 'all-classruns',
  ClassRunInfoTab = 'classrun-info',
  ClassRunContentTab = 'classrun-content',
  ParticipantsTab = 'participants',
  AssignmentsTab = 'assignments',
  AttendanceTrackingTab = 'attendance-tracking',
  AssignmentInfoTab = 'assignment-info',
  SessionInfoTab = 'session-info',
  AssigneesTab = 'assignees',
  LearningPathsTab = 'learning-paths',
  LearningPathInfoTab = 'learning-path-info',
  CourseStatisticTab = 'course-statistic',
  QuizStatisticTab = 'quiz-statistic',
  AssignmentStaticticTab = 'assignment-statistic',
  PostCourseStatisticTab = 'post-course-statistic',
  PreCourseStatisticTab = 'pre-course-statistic',
  PersonalInfoTab = 'personal-info',
  LearnerAssignmentAnswerTab = 'learner-assigment-answer',
  CourseCommentTab = 'course-comment',
  ClassRunCommentTab = 'classrun-comment',
  LearnerAssignmentAnswerCommentTab = 'learner-assignment-answer-comment',
  ReportBrokenLinkTab = 'report-broken-link',
  NewAnnouncementTab = 'new-announcement',
  AnnouncementTab = 'announcement',
  DigitalLearnerTab = 'digital-learner',
  ReflectiveLearnerTab = 'reflective-learner',
  ActiveContributorTab = 'active-contributor',
  LifeLongLearnerTab = 'life-long-learner',
  AssessmentTab = 'assessment',
  PeerAssessmentTab = 'peer-assessment'
}
