https_proxy: http://proxy.opal:3128
mssql_username: prod-standalonesurvey-opal-db-readwrite
mssql_password: kUMC8MzTjQYedAs
mssql_host: mssql.opal
OpalClientUrl: "https://www.opal2.moe.edu.sg/app/"
Logging_LogLevel_Default: Error
GetAccessRightsUrl: http://prod-competence-opal-api-portal.opal/me/accessRights
DeveloperExceptionEnabled: false
RabbitMQOptions_QueueName: prod-microservice-opal-queue-standalonesurvey
RabbitMQOptions_ExchangeName: prod-datahub-opal-topic-event
RabbitMQOptions_RetryCount: 2
RabbitMQOptions_RetryPolicyInSeconds: 5
RabbitMQOptions_DefaultCommandExchange: prod-datahub-opal-topic-command
RabbitMQOptions_DefaultEventExchange: prod-datahub-opal-topic-event
RabbitMQOptions_DefaultActivityExchange: prod-datahub-opal-topic-activity
RabbitMQOptions_DefaultAuditLogExchange: prod-opal-topic-auditlog
RabbitMQOptions_DefaultIntegrationExchange: prod-opal-topic-integration
HangfireDatabaseUsername: prod-cx-opal-scheduling-jobs-db-readwrite
HangfireDatabasePassword: kUMC8MzTjQYedAs
