version: '2.4'

services:
  domain-api-organization:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT_NAME}
      - BuildVersion=${GO_PIPELINE_LABEL}
      - VIRTUAL_HOST=${ENVIRONMENT_NAME}-competence-${PROJECT_NAME}-api-organization.${DOMAIN_POSTFIX}${PUBLIC_DNS}
      - AppSettings:AuthorityUrl={{ idm_base_url }}
      - AppSettings:ApiBaseUrl=http://api.opal
      - AppSettings:PortalAPI=${ENVIRONMENT_NAME}-competence-${PROJECT_NAME}-api-portal
      - AppSettings:IsCrossOrganizationalUnit={{ is_cross_organizational_unit }}
      - AppSettings:ServiceUsername={{ service_username }}
      - AppSettings:ServicePassword={{ service_password }}
      - AppSettings:AdminUsername={{ admin_username }}
      - AppSettings:AdminPassword={{ admin_password }}
      - AppSettings:OwnerId=3001
      - AppSettings:SiteId=1
      - AppSettings:HDId=2
      - AppSettings:CurrentUserId=1
      - AppSettings:SSN_REGEX=^[a-zA-Z0-9._-]+$$
      - AppSettings:OPALMainPageLink={{ opal_main_page_link }}
      - AppSettings:SAMLink={{ sam_link }}
      - AppSettings:PDPMLink={{ pdpm_link }}
      - AppSettings:LogoPath={{ logo_path }}
      - AppSettings:LearnerWebAppLink={{ learner_web_app_link }}
      - AppSettings:LearnerAndroidAppLink={{ learner_android_app_link }}
      - AppSettings:LearnerIOSAppLink={{ learner_ios_app_link }}
      - DatahubLog:Enable=true
      - AppSettings:EnableMigration={{ enable_migration }}
      - DatahubLog:EventChannel:Enable=true
      - DatahubLog:EventChannel:Exchange=${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-topic-event
      - DatahubLog:CommandChannel:Enable=true
      - DatahubLog:CommandChannel:Exchange=${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-topic-command
      - DatahubLog:CommandChannel:RoutingKey=command
      - PROJECT_NAME=${PROJECT_NAME}
      - ConnectionStrings:DefaultConnection=Data Source=${MSSQL2_HOSTNAMES};Initial Catalog={{ aspnetcore_environment }}-competence-${PROJECT_NAME}-at6qr;User ID={{ mssql_username }};Password={{ mssql_password }}
      - ConnectionStrings:Hangfire=Data Source=${MSSQL2_HOSTNAMES};Initial Catalog={{ hangfireDatabase }};User ID={{ hangfireDatabaseUsername }};Password={{ hangfireDatabasePassword }}
      - IDM_SCOPE=userManagement cxDomainInternalApi
      - IDM_GRANT_TYPE=client_credentials
      - RABBITMQ_HOSTNAMES=${RABBITMQ_HOSTNAMES}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - QUEUE_NAME=${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-queue-organization_api
      - EVENT_EXCHANGE_NAME=${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-topic-event
      - COMMAND_EXCHANGE_NAME=${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-topic-command
      - RABBITMQ_SSL_ENABLED=${RABBITMQ_SSL_ENABLED}
      - RABBITMQ_PORT=5672
      - NOLOCK_ENABLE={{ enable_nolock }}
      - QUEUE_MANAGER_API=http://${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-api-queuemanager.${DOMAIN_POSTFIX}/QueueManager
      - IDM_BASEURL=${IDM_INTERNAL_URL}
      - IDM_INTERNAL_URL=${IDM_INTERNAL_URL}
      - IDM_CLIENT_ID=cxDomainInternalApi
      - IDM_CLIENT_SECRET=AiOiJKV1QiLCJ4NXQiOiJhM
      - Serilog:Properties:sitename=${ENVIRONMENT_NAME}-competence-${PROJECT_NAME}-api-organization
      - Serilog:MinimumLevel:Default=${APPLICATION_LOG_LEVEL}
      - Serilog:MinimumLevel:Override:Microsoft=${FRAMEWORK_LOG_LEVEL}
      - Serilog:MinimumLevel:Override:System=${FRAMEWORK_LOG_LEVEL}
      - BusinessConfigs:UserNotification:UserTypePending2ndNotification={{ BusinessConfigs_UserNotification_UserTypePending2ndNotification }}
      - BusinessConfigs:UserNotification:UserTypePending3ndNotification={{ BusinessConfigs_UserNotification_UserTypePending3ndNotification }}
      - BusinessConfigs:UserNotification:UserTypeSyncIdpNotification={{ BusinessConfigs_UserNotification_UserTypeSyncIdpNotification }}
      - SECRETBOX_KEY={{ secretbox_key }}
      - SECRETBOX_NONCE={{ secretbox_nonce }}
      - DataHubQueryAPISettings:APIBaseUrl=http://${ENVIRONMENT_NAME}-datahub-${PROJECT_NAME}-api-query.${DOMAIN_POSTFIX}
      - DataHubQueryAPISettings:APIAuthorization={{ domain_api_auth }}
      - AwsSettings:AccessKey=${S3_ORG_API_KEY}
      - AwsSettings:SecretKey=${S3_ORG_API_SECRET}
      - AwsSettings:Region={{ aws_region }}
      - AwsSettings:BucketName={{ aws_bucket_name }}
      - EmailTemplates:UserEmailTemplates:SignUpEmail:CommunicationApiTemplate:templateName={{ signup_email_temaplate }}
      - EmailTemplates:ExportUserTemplate:CommunicationApiTemplate:data:DownloadUrl={{ sam_link }}/user-accounts/report?filepath={filepath}
      - EmailTemplates:ExportUserEventLogTemplate:CommunicationApiTemplate:data:DownloadUrl={{ sam_link }}/reports?filepath={filepath}
      - EmailTemplates:ExportUserStatisticTemplate:CommunicationApiTemplate:data:DownloadUrl={{ sam_link }}/reports?filepath={filepath}
      - EmailTemplates:ExportApprovingTemplate:CommunicationApiTemplate:data:DownloadUrl={{ sam_link }}/reports?filepath={filepath}
      - EmailTemplates:ExportUserAccountDetailsTemplate:CommunicationApiTemplate:data:DownloadUrl={{ sam_link }}/reports?filepath={filepath}
      - EmailTemplates:ExportPrivilegedUserAccountTemplate:CommunicationApiTemplate:data:DownloadUrl={{ sam_link }}/reports?filepath={filepath}
      - REDIS_CONNECTIONSTRING={{ redis_connectionstring }}
      - CacheSettings:DistributedMemoryCache:Enable=true
      - LearningCatalogAPISettings:APIBaseUrl=http://${ENVIRONMENT_NAME}-competence-${PROJECT_NAME}-api-learningcatalog.${PROJECT_NAME}/
      - Idm_ApiName=${INTERNAL_DOMAIN_API_NAME}
      - Idm_ApiSecret=${INTERNAL_DOMAIN_API_SECRET}
      - AwsKmsEncyption:Enabled={{ AwsKmsEncyption_Enabled }}
      - AwsKmsEncyption:AwsAccessKey={{ AwsKmsEncyption_AwsAccessKey }}
      - AwsKmsEncyption:AwsSecretKey={{ AwsKmsEncyption_AwsSecretKey }}
      - AwsKmsEncyption:KmsArn={{ AwsKmsEncyption_KmsArn }}
      - AwsKmsEncyption:EncryptedHashKey={{ AwsKmsEncyption_EncryptedHashKey }}
{% if https_proxy is defined %}
      - HTTPS_PROXY={{ https_proxy }}
{% endif %}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    ports:
      - 0:80
networks:
  default:
    external:
      name: ${PROJECT_NAME}_default