/**
 * Please dont change this file. If you want change it, you must update deeplink for Front-end/Back-end
 */
export enum CAMTabConfiguration {
  CoursesTab = 'courses',
  HasCoursePendingApprovalTab = 'pending-course-approval',
  HasPendingClassApprovalCourseTab = 'pending-class-course-approval',
  HasPendingRegistrationApprovalCourseTab = 'pending-registration-course-approval',
  ArchivalTab = 'archival',
  CourseInfoTab = 'course-info',
  ClassRunsTab = 'classruns',
  AllClassRunsTab = 'all-classruns',
  CancellationRequestsTab = 'cancellation-requests',
  RescheduleRequestsTab = 'reschedule-requests',
  HasPendingRegistrationApprovalClassrunTab = 'pending-registration-classrun-approval',
  ClassRunInfoTab = 'classrun-info',
  SessionsTab = 'sessions',
  RegistrationsTab = 'registrations',
  ParticipantsTab = 'participants',
  WaitlistTab = 'wait-list',
  WithdrawalRequestsTab = 'withdrawal-requests',
  SessionInfoTab = 'session-info',
  StatisticTab = 'statistic',
  CourseStatisticTab = 'course-statistic',
  ChangeClassRunRequestsTab = 'change-classrun-requests',
  PersonalInfoTab = 'personal-info',
  PlanningCycleTab = 'planning-cycle',
  CoursePlanningCycleInfoTab = 'course-planning-cycle-info',
  CoursesOfPlanningCycleTab = 'courses-of-planning-cycle',
  BlockoutDateTab = 'blockout-date',
  AllCoursesOfPlanningCycleTab = 'all-courses-of-planning-cycle',
  CoursePendingApprovalOfPlanningCycleTab = 'course-pending-approval-of-planning-cycle',
  CoursePendingVerifyOfPlanningCycleTab = 'course-pending-verify-of-planning-cycle',
  AddingParticipantTab = 'adding-participant',
  SendCoursePublicityTab = 'send-course-publicity',
  SendCourseNominationTab = 'send-course-nomination',
  CourseCriteriaTab = 'course-criteria',
  SendOrderRefreshmentTab = 'send-order-refreshment',
  CourseCommentTab = 'course-comment',
  ClassRunCommentTab = 'classrun-comment',
  AllBlockoutDateTab = 'all-blockout-date',
  AllECertificateTab = 'all-ecertificate',
  IssuanceTrackingTab = 'issuance-tracking',
  ECertificateInfoTab = 'ecertificate-info'
}
