IF OBJECT_ID(N'opa.Migration_Course', N'U') IS NULL
BEGIN
CREATE TABLE opa.Migration_Course(
	[Id] [uniqueidentifier] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[ChangedDate] [datetime2](7) NULL,
	[DeletedDate] [datetime2](7) NULL,
	[Version] [varchar](10) NULL,
	[CourseCode] [varchar](30) NULL,
	[CourseName] [nvarchar](450) NOT NULL,
	[CourseType] [varchar](30) NULL,
	[CourseContent] [nvarchar](max) NULL,
	[CourseLevel] [varchar](20) NULL,
	[Description] [nvarchar](max) NULL,
	[CourseObjective] [nvarchar](max) NULL,
	[DurationMinutes] [int] NOT NULL,
	[Price] [decimal](18, 2) NULL,
	[ThumbnailUrl] [varchar](300) NULL,
	[TrailerVideoUrl] [varchar](300) NULL,
	[TermsOfUse] [nvarchar](4000) NULL,
	[CourseSourceId] [uniqueidentifier] NULL,
	[CourseCollectionId] [uniqueidentifier] NULL,
	[CopyRightId] [uniqueidentifier] NULL,
	[IsExternalCourse] [bit] NOT NULL,
	[ExternalCourseId] [varchar](450) NULL,
	[ExternalSourceId] [varchar](450) NULL,
	[CourseCompletionStatus] [varchar](20) NULL,
	[Status] [varchar](11) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Priority] [int] NULL,
	[ApprovingOfficer] [varchar](50) NULL,
	[ApprovingOfficerComment] [nvarchar](max) NULL,
	[IsAutoPublish] [bit] NULL,
	[IsAllowDownload] [bit] NOT NULL,
	[ExternalId] [varchar](255) NULL,
	[StartDate] [datetime2](7) NULL,
	[EndDate] [datetime2](7) NULL,
	[EndOfRegistration] [datetime2](7) NULL,
	[PublishDate] [datetime2](7) NULL,
	[CreatedBy] [uniqueidentifier] NOT NULL,
	[ChangedBy] [uniqueidentifier] NOT NULL,
	[ParentId] [uniqueidentifier] NULL,
	[ParentType] [int] NOT NULL,
	[Order] [int] NULL,
	[ExpiredDate] [datetime2](7) NULL,
	[Copyright] [nvarchar](100) NULL,
	[Publisher] [nvarchar](100) NULL,
	[Source] [nvarchar](255) NULL,
	[AcknowledgementAndCredit] [nvarchar](4000) NULL,
	[IsAllowModification] [bit] NOT NULL,
	[IsAllowReusable] [bit] NOT NULL,
	[LicenseTerritory] [varchar](30) NOT NULL,
	[LicenseType] [varchar](36) NOT NULL,
	[Ownership] [varchar](40) NOT NULL,
	[Remarks] [nvarchar](4000) NULL,
	[AttributionUrl] [nvarchar](500) NULL,
	PRIMARY KEY(Id)
	)
END