export const PLAYER_ACCESS_TOKEN_KEY: string = 'PLAYER_ACCESS_TOKEN_KEY';
export const PLAYER_CONTENT_ID_KEY: string = 'PLAYER_CONTENT_ID_KEY';
export const PLAYER_LECTURE_ID_KEY: string = 'PLAYER_LECTURE_ID_KEY';
export const PLAYER_CLASSRUN_ID_KEY: string = 'PLAYER_CLASSRUN_ID_KEY';
export const PLAYER_MY_LECTURE_ID_KEY: string = 'PLAYER_MY_LECTURE_ID_KEY';
export const PLAYER_DISPLAY_MODE_KEY: string = 'PLAYER_DISPLAY_MODE_KEY';
export const PLAYER_DISABLE_FULLSCREEN_KEY: string = 'PLAYER_DISABLE_FULLSCREEN_KEY';
export const PLAYER_FULLSCREEN_CALLBACK_KEY: string = 'PLAYER_FULLSCREEN_CALLBACK_KEY';

export const PLAYER_LOCAL_STORAGE_KEYS = [
  PLAYER_ACCESS_TOKEN_KEY,
  PLAYER_CONTENT_ID_KEY,
  PLAYER_LECTURE_ID_KEY,
  PLAYER_CLASSRUN_ID_KEY,
  PLAYER_MY_LECTURE_ID_KEY,
  PLAYER_DISPLAY_MODE_KEY,
  PLAYER_DISABLE_FULLSCREEN_KEY,
  PLAYER_FULLSCREEN_CALLBACK_KEY
];
