// tslint:disable-next-line:variable-name
export const JobKeys = [
  'N/A',
  'Accounting Prof',
  'Administration Manager',
  'Administrative Executive',
  'Asst Dir',
  'Branch Head',
  'Corporate Support Officer',
  'Dir',
  'Dir-Gen',
  'Divisional Head',
  'Driver',
  'Dy Dir',
  'Head of Dept',
  'Head of Dept, Larger Portfolio',
  'Level Head',
  'Manager',
  'Master Teacher',
  'Mechanical Support Officer',
  'Operations Manager',
  'Operations Support Officer',
  'Personal Asst',
  'Principal',
  'Quality Assessor',
  'Section Head',
  'Snr Quality Assessor',
  'Snr Specialist',
  'Snr Teacher',
  'Staff Officer',
  'Subject Head',
  'Superintendent',
  'Teacher',
  'AVA Technician',
  'Translator',
  'Unit Head',
  'Vice-Principal',
  'Vice Principal (Administration)',
  'Deputy Secretary',
  'Education Workshop Instructor',
  'School Laboratory Technician',
  'Estate Maintenance Officer',
  'Librarian',
  'Technical Manager',
  'Technical Supervisor',
  'Technician',
  'Typist',
  'Special Needs Officer',
  'Full-Time School Counsellor',
  'Co-Curricular Planning Executive',
  'Education Associate',
  'School Counsellor',
  'Allied Educator (LBS)',
  'Allied Educator (TL)',
  'School Staff Developer',
  'Allied Educator, TL Prog fr Act Learning',
  'Lead Teacher',
  'Principal Master Teacher',
  'Technical Support Officer',
  'Management Support Officer',
  'Lead Specialist',
  'Principal Specialist',
  'Chief Specialist',
  'Deputy DGE',
  'Group Director (EAS)',
  'International Teaching Associate',
  'Partnerships Liaison Manager',
  'Chief School Counsellor (CSC)',
  'Master School Counsellor (MSC)',
  'Lead School Counsellor (LSC)',
  'Senior School Counsellor (SSC)',
  'Lead AED (T&L)',
  'Senior AED (LBS)',
  'Senior AED (T&L)',
  'Lead Allied Educator, TL Prog FAL',
  'Senior Allied Educator, TL Prog FAL',
  'Year Head',
  'Principal (LC)',
  'Unit Head (EAS)',
  'Unit Head (Edun Offr)',
  'Section Head (EAS)',
  'Section Head (Edun Offr)',
  'Branch Head (EAS)',
  'Branch Head (Edun Offr)',
  'Division Head (EAS)',
  'Division Head (Edun Offr)',
  'Group Director (Edun Offr)',
  'ICT Manager',
  'ICT Associate',
  'MK Centre Head',
  'MK Deputy Centre Head',
  'MK Level Head',
  'MK Senior Teacher',
  'MK Teacher',
  'MK Mentor Teacher',
  'Assistant Year Head',
  'Allied Educator (OAE)',
  'Senior Allied Educator (OAE)',
  'Lead Allied Educator (OAE)',
  'Master Allied Educator (OAE)',
  'Master Specialist',
  'Student Welfare Officer',
  'Senior Student Welfare Officer',
  'Lead Student Welfare Officer',
  'Master Student Welfare Officer',
  'Chief Student Welfare Officer'
];
