docker_image: "cx-domain-api-organization:1.0.3"
aspnetcore_environment: prod
mssql_username: prod-competence-opal-at6qr-readwrite
mssql_password: kMzTCsUMC88jQYedAs
mssql_host: mssql.opal
BusinessConfigs_UserNotification_UserTypePending2ndNotification: "145"
BusinessConfigs_UserNotification_UserTypePending3ndNotification: "112"
BusinessConfigs_UserNotification_UserTypeSyncIdpNotification: "87,88,89"
idm_base_url: https://idm.opal2.moe.edu.sg
is_cross_organizational_unit: false
enable_migration: true
domain_api_auth: "Basic QXp4Y25tYXNrbGRqdnExd2E6anZ4bWFza2NuQXExd2F6bGQ="
https_proxy: http://proxy.opal:3128
opal_main_page_link: "https://www.opal2.moe.edu.sg"
pdpm_link: "https://www.opal2.moe.edu.sg"
sam_link: "https://admin.opal2.moe.edu.sg"
logo_path: "https://admin.opal2.moe.edu.sg/assets/images/opal.png"
learner_web_app_link: "https://www.opal2.moe.edu.sg/app/learner"
learner_android_app_link: "https://play.google.com/store/apps/details?id=com.opal2.moe.edu.sg"
learner_ios_app_link: "https://apps.apple.com/us/app/opal2.0/id1498577305"
secretbox_key: 12345678901234567890123456789012
secretbox_nonce: ABCDEFGHIJKLMNOPQRSTUVWX
service_username: Azxcnmaskldjvq1wa
service_password: jvxmaskcnAq1wazld
admin_username: jvxmaskcnAqdx1wazlmaskc
admin_password: wazlxmaskcjmaskcnAqvdx1
enable_nolock: true
aws_region: ap-southeast-1
aws_bucket_name: prod-internal-opal-content
signup_email_temaplate: SignUpEmail
hangfireDatabase: prod-cx-opal-scheduling-jobs-db
hangfireDatabaseUsername: prod-cx-opal-scheduling-jobs-db-readwrite
hangfireDatabasePassword: kUMC8MzTjQYedAs
redis_connectionstring: redis.opal:6379,ConnectTimeout=5000,abortConnect=false
AwsKmsEncyption_Enabled: true
AwsKmsEncyption_AwsAccessKey: AKIA6KUBMYDLJECARWE5
AwsKmsEncyption_AwsSecretKey: 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
AwsKmsEncyption_KmsArn: "arn:aws:kms:ap-southeast-1:984892621014:key/f4a2f427-8014-4b6d-9d4c-905ded939d45"
AwsKmsEncyption_EncryptedHashKey: "AQECAHginPN8fcfVeyDY/oUrCy6BbXmeIdvw/iEYjX0xjmA/7wAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJ7B/B+0M3CaQWo4dQIBEIAvN0dJylkLZhINNFsNXUo2eGvXJZkP0DrCxPu2JpX9AtXeWHDiYPe0bq5aLfoXi3M="