export const CCPM_PERMISSIONS = {
  // DIGITAL CONTENT
  AccessContentRepo: 'CCPM.DigitalContent',
  ViewListContent: 'CCPM.DigitalContent.ViewList',
  ViewListSubmittedContent: 'CCPM.DigitalContent.ViewListSubmittedRequest',
  ViewListArchivedContent: 'CCPM.DigitalContent.ViewListArchived',
  CreateContent: 'CCPM.DigitalContent.Create',
  DuplicateContent: 'CCPM.DigitalContent.Duplicate',
  RenameContent: 'CCPM.DigitalContent.Rename',
  DeleteContent: 'CCPM.DigitalContent.Delete',
  EditContent: 'CCPM.DigitalContent.Edit',
  ArchiveContent: 'CCPM.DigitalContent.Archive',
  SubmitForApproveContent: 'CCPM.DigitalContent.SubmitForApproval',
  ApproveContent: 'CCPM.DigitalContent.Approve',
  RejectContent: 'CCPM.DigitalContent.Reject',
  PublishContent: 'CCPM.DigitalContent.Publish',
  UnPublishContent: 'CCPM.DigitalContent.UnPublish',
  MarkAsReadyContent: 'CCPM.DigitalContent.MarkAsReady',
  TransferOwnerShipContent: 'CCPM.DigitalContent.TransferOwnership',
  MarkAsDraftContent: 'CCPM.DigitalContent.MarkAsDraft',

  // FORM
  AccessFormRepo: 'CCPM.Form',
  ViewListForm: 'CCPM.Form.ViewList',
  ViewListSubmittedForm: 'CCPM.Form.ViewListSubmittedRequest',
  ViewListArchivedForm: 'CCPM.Form.ViewListArchived',
  CreateForm: 'CCPM.Form.CreateForm',
  DuplicateForm: 'CCPM.Form.Duplicate',
  RenameForm: 'CCPM.Form.Rename',
  DeleteForm: 'CCPM.Form.Delete',
  EditForm: 'CCPM.Form.Edit',
  ArchiveForm: 'CCPM.Form.Archive',
  SubmitForApproveForm: 'CCPM.Form.SubmitForApproval',
  ApproveForm: 'CCPM.Form.Approve',
  RejectForm: 'CCPM.Form.Reject',
  PublishForm: 'CCPM.Form.Publish',
  UnPublishForm: 'CCPM.Form.Unpublish',
  MarkAsReadyForm: 'CCPM.Form.MarkAsReady',
  TransferOwnerShipForm: 'CCPM.Form.TransferOwnership',
  EnableStandalone: 'CCPM.Form.EnableStandalone',
  EnablePublicModeStandalone: 'CCPM.Form.EnablePublicModeStandalone',
  MarkAsDraftForm: 'CCPM.Form.MarkAsDraft'
};
