export enum StatusActionTypeEnum {
  Active = 'Active',
  Unlock = 'Unlock',
  ResetPassword = 'ResetPassword',
  Accept = 'Accept',
  Reject = 'Reject',
  CreateAccount = 'CreateAccount',
  SetExpirationDate = 'SetExpirationDate',
  SetApprovingOfficers = 'SetApprovingOfficers',
  Remove = 'Remove',
  RequestSpecialApproval = 'RequestSpecialApproval',
  Suspend = 'Suspend',
  AddToGroup = 'AddToGroup',
  Edit = 'Edit',
  ShowHideColumn = 'ShowHideColumn',
  Export = 'Export',
  ExportAll = 'ExportAll',
  Reminder = 'Reminder',
  AssignLearningNeeds = 'AssignLearningNeeds',
  Nominate = 'Nominate',
  ExportLearningNeedsAnalysis = 'ExportLearningNeedsAnalysis',
}
