version: '2.4'

services:
  webinarautoscaler-api:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT_NAME}
      - BuildVersion=${GO_PIPELINE_LABEL}
      - VIRTUAL_HOST=${ENVIRONMENT_NAME}-learnapp-${PROJECT_NAME}-api-webinarautoscaler.${DOMAIN_POSTFIX}
      - DeveloperExceptionEnabled={{ DeveloperExceptionEnabled }}
      - ConnectionStrings:Default=Data Source=${MSSQL_HOSTNAMES};Initial Catalog=${ENVIRONMENT_NAME}-webinarautoscaler-${PROJECT_NAME}-db;User ID={{ mssql_username }};Password={{ mssql_password }}

      - RabbitMQOptions:HostNames=${RABBITMQ_HOSTNAMES}
      - RabbitMQOptions:UserName=${RABBITMQ_USERNAME}
      - RabbitMQOptions:Password=${RABBITMQ_PASSWORD}
      - RabbitMQOptions:SslEnabled=${RABBITMQ_SSL_ENABLED}
      - RabbitMQOptions:QueueName={{ RabbitMQOptions_QueueName }}
      - RabbitMQOptions:ExchangeName={{ RabbitMQOptions_ExchangeName }}
      - RabbitMQOptions:RetryCount={{ RabbitMQOptions_RetryCount }}
      - RabbitMQOptions:RetryPolicyInSeconds={{ RabbitMQOptions_RetryPolicyInSeconds }}
      - RabbitMQOptions:DefaultCommandExchange={{ RabbitMQOptions_DefaultCommandExchange }}
      - RabbitMQOptions:DefaultEventExchange={{ RabbitMQOptions_DefaultEventExchange }}
      - RabbitMQOptions:DefaultActivityExchange={{ RabbitMQOptions_DefaultActivityExchange }}
      - RabbitMQOptions:DefaultAuditLogExchange={{ RabbitMQOptions_DefaultAuditLogExchange }}
      - RabbitMQOptions:DefaultIntegrationExchange={{ RabbitMQOptions_DefaultIntegrationExchange }}

      - AWSOptions:AccessKey=${AWS_WEBINAR_ACCESS_KEY}
      - AWSOptions:SecretKey=${AWS_WEBINAR_SECRET_KEY}
      - AWSOptions:Region=${AWS_WEBINAR_REGION}    
      - AWSOptions:TargetGroupVPC=${AW_WEBINAR_TARGET_GROUP_VPC}
      - AWSOptions:WebinarDns=${AWS_WEBINAR_WEBINAR_DNS}
      - Logging:LogLevel:Default=${APPLICATION_LOG_LEVEL}
      - Logging:LogLevel:Microsoft=${FRAMEWORK_LOG_LEVEL}
      - GetAccessRightsUrl={{GetAccessRightsUrl}}

{% if https_proxy is defined %}
      - HTTPS_PROXY={{ https_proxy }}
      - HTTP_PROXY={{ https_proxy }}
      - NO_PROXY=localhost,.opal
{% endif %}
    container_name: ${ENVIRONMENT_NAME}-webinarautoscaler-${PROJECT_NAME}-api
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    ports:
      - 0:80
networks:
  default:
    external:
      name: ${PROJECT_NAME}_default
