export enum MetadataTagGroupCode {
  PDO_TYPES = 'PDO-TYPES',
  SERVICE_SCHEMES = 'SERVICESCHEMES',
  PDO_CATEGORIES = 'PDO-CATEGORIES',
  PDO_MODES = 'PDO-MODES', // MODE OF LEARNING
  PDO_NATURES = 'PDO-NATURES', // NATURE OF COURSE
  COURSE_LEVELS = 'COURSE-LEVELS',
  DEVROLES = 'DEVROLES',
  PDO_TAXONOMY = 'PDO-TAXONOMY', // Subject Areas
  LEARNING_FXS = 'LEARNING-FXS', // LEARNING FRAMEWORKS
  TRACKS = 'TRACKS',
  TEACHING_SUBJECTS = 'TEACHING-SUBJECTS',
  TEACHING_LEVELS = 'TEACHING-LEVELS',
  JOB_FAMILIES = 'JOB-FAMILIES',
  COURSES_OF_STUDY = 'COURSES-OF-STUDY',
  CO_CURRICULAR_ACTIVITIES = 'CCAS',
  PERIOD_PD_ACTIVITY = 'PDO-PERIODS',
  DESIGNATION = 'DESIGNATION'
}
