export enum UserEventType {
  Unknown = 'Unknown',
  RegisteredSuccess = 'RegisteredSuccess',
  DeletedSuccess = 'DeletedSuccess',
  LoginSuccess = 'LoginSuccess',
  LoginFail = 'LoginFail',
  LogoutSuccess = 'LogoutSuccess',
  LogoutFail = 'LogoutFail',
  Locked = 'Locked',
  ResetPasswordSuccess = 'ResetPasswordSuccess',
  ChangePasswordSuccess = 'ChangePasswordSuccess',
  SetPasswordSuccess = 'SetPasswordSuccess',
  ForgetPasswordSuccess = 'ForgetPasswordSuccess',
  ForgetPasswordFail = 'ForgetPasswordFail',
  ClaimOtpEmailSuccess = 'ClaimOtpEmailSuccess',
  ClaimOtpEmailFail = 'ClaimOtpEmailFail',
  ClaimOtpPhoneSuccess = 'ClaimOtpPhoneSuccess',
  ClaimOtPhoneFail = 'ClaimOtPhoneFail',
  Claim2faSuccess = 'Claim2faSuccess',
  Claim2faFail = 'Claim2faFail',
  Verify2faSuccess = 'Verify2faSuccess',
  Verify2faFail = 'Verify2faFail',
  Enable2faSuccess = 'Enable2faSuccess',
  Disable2faSuccess = 'Disable2faSuccess'
}
