mongo_db_name: prod-communication-opal-db
mongo_db_auth: prod-communication-opal:opal-communication-prod
https_proxy: http://proxy.opal:3128
HangfireDatabase: prod-cx-opal-scheduling-jobs-db
HangfireDatabaseUsername: prod-cx-opal-scheduling-jobs-db-readwrite
HangfireDatabasePassword: kUMC8MzTjQYedAs