https_proxy: http://proxy.opal:3128
mssql_username: prod-tagging-opal-db-readwrite
mssql_password: kUMC8MzTjQYedAs
mssql_host: mssql.opal
Logging_LogLevel_Default: Error
GetAccessRightsUrl: http://prod-competence-opal-api-portal.opal/me/accessRights
DeveloperExceptionEnabled: false
Authentication_AuthorityUrl: https://idm.opal2.moe.edu.sg
Authentication_ClientId: cxDomainInternalApi
Authentication_ClientSecret: AiOiJKV1QiLCJ4NXQiOiJhM
MetadataSynchronizer_ApiOriginUrl: http://prod-competence-opal-api-learningcatalog.opal
RabbitMQOptions_QueueName: prod-microservice-opal-queue-metadata
RabbitMQOptions_ExchangeName: prod-datahub-opal-topic-event
RabbitMQOptions_RetryCount: 2
RabbitMQOptions_RetryPolicyInSeconds: 5
RabbitMQOptions_DefaultCommandExchange: prod-datahub-opal-topic-command
RabbitMQOptions_DefaultEventExchange: prod-datahub-opal-topic-event
RabbitMQOptions_DefaultActivityExchange: prod-datahub-opal-topic-activity
