https_proxy: http://proxy.opal:3128
mssql_username: prod-webinar-opal-db-readwrite
mssql_password: kUMC8MzTjQYedAs
mssql_host: mssql.opal
OpalAuthority: "https://idm.opal2.moe.edu.sg"
OpalClientUrl: "https://www.opal2.moe.edu.sg/app/"
DeveloperExceptionEnabled: false
Logging_LogLevel_Default: Error
GetAccessRightsUrl: http://prod-competence-opal-api-portal.opal/me/accessRights
RabbitMQOptions_QueueName: prod-microservice-opal-queue-webinar
RabbitMQOptions_ExchangeName: prod-datahub-opal-topic-event
RabbitMQOptions_RetryCount: 2
RabbitMQOptions_RetryPolicyInSeconds: 5
RabbitMQOptions_DefaultCommandExchange: prod-datahub-opal-topic-command
RabbitMQOptions_DefaultEventExchange: prod-datahub-opal-topic-event
RabbitMQOptions_DefaultActivityExchange: prod-datahub-opal-topic-activity
RabbitMQOptions_DefaultAuditLogExchange: prod-opal-topic-auditlog
RabbitMQOptions_DefaultIntegrationExchange: prod-opal-topic-integration                       
HangfireDatabaseUsername: prod-cx-opal-scheduling-jobs-db-readwrite
HangfireDatabasePassword: kUMC8MzTjQYedAs
BigBlueButtonServerOptions_WebinarUrl: https://webinar.opal2.moe.edu.sg
BigBlueButtonServerOptions_ProxyUrl: https://webinar.opal2.moe.edu.sg/session/api
BigBlueButtonServerOptions_CloudfrontUrl: https://d32u4p9rbaq5ex.cloudfront.net
BigBlueButtonServerOptions_WaitingServerPageUrl:  https://www.opal2.moe.edu.sg/app/common/meeting
