INSERT INTO [MyAssignments](
	[Id]
      ,[CreatedDate]
      ,[ChangedDate]
      ,[DeletedDate]
      ,[RegistrationId]
      ,[UserId]
      ,[AssignmentId]
      ,[Status]
      ,[CreatedBy]
      ,[ChangedBy]
      ,[IsDeleted]
      ,[SubmittedDate]
      ,[EndDate]
      ,[StartDate])
  SELECT [Id]
      ,[CreatedDate]
      ,[ChangedDate]
      ,[DeletedDate]
      ,[RegistrationId]
      ,[UserId]
      ,[AssignmentId]
      ,[Status]
      ,[CreatedBy]
      ,[ChangedBy]
      ,[IsDeleted]
      ,[SubmittedDate]
      ,[EndDate]
      ,[StartDate] from [uat-next-courses-opal-db].[dbo].[ParticipantAssignmentTrack]