const appUrl: string = `${window.location.origin}/app`;

export const environment: IEnvironment = {
  envName: 'systemtest',
  production: true,
  manifest: 'assets/manifest.json',
  appUrl,
  apiUrl: '',

  contentApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-content/api',
  courseApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-course/api',
  formApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-form/api',
  learnerApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-learner/api',
  uploaderApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-uploader/api',
  taggingApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-tagging/api',
  brokenLinkApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-brokenlink/api',
  calendarApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-calendar/api',
  newsfeedApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-newsfeed/api',
  webinarApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-webinar/api',
  lnaFormApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-lnaform/api',
  badgeApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-badge/api',

  cslApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-socialapp-opal-csl-api/api',
  cloudfrontApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-learnapp-opal-api-cloudfront/api',
  cloudfrontUrl: 'https://d160tkrk8an3tz.cloudfront.net',
  scormPlayerUrl: `https://d160tkrk8an3tz.cloudfront.net/permanent/scorm-player/scorm-player.html`,
  userOnboardingUrl: `https://www.systemtest.opal2.conexus.net/opal-account/opal-account/onboarding?returnUrl=${appUrl}/learner`,
  reportVulnerabilityUrl: 'https://www.tech.gov.sg/report_vulnerability',
  privacyPolicyUrl: 'https://idm.uat.opal2.conexus.net/Home/PrivacyPolicy',
  termOfUse: 'https://idm.uat.opal2.conexus.net/Home/TermsOfUse',
  competenceApiUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api',
  learningCatalogUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api-learningcatalog',
  reportUrl: 'https://www.systemtest.opal2.conexus.net/report',
  AESSecretKey: '92AE31A79FEEB2A3',
  AESIv: 'H+MbQeThWmZq4t7w',
  ePortfolioUrl: 'https://www.systemtest.opal2.conexus.net/eportfolio',
  pdplanUrl: 'https://www.systemtest.opal2.conexus.net/pdplanner',
  cslUrl: 'https://www.systemtest.opal2.conexus.net/csl',
  notificationUrl: 'https://www.systemtest.opal2.conexus.net/opal-account/notifications/bell',
  broadcastMessageNotificationUrl: 'https://www.systemtest.opal2.conexus.net/opal-account/notifications/alert',
  enableBroadcastMessage: false,
  enableBellNotification: true,
  authConfig: {
    strictDiscoveryDocumentValidation: false,
    requireHttps: false,
    responseType: 'code',
    issuer: 'https://idm.systemtest.opal2.conexus.net',
    logoutUrl: 'https://idm.systemtest.opal2.conexus.net/connect/endsession',
    profileUrl: 'https://www.systemtest.opal2.conexus.net/opal-account/opal-account/profile',
    changePasswordUrl: 'https://idm.systemtest.opal2.conexus.net/Manage/ChangePassword',
    sitesUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api-portal/sites',
    organizationUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api-organization',
    permissionUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api-portal/me/accessRights',
    postLogoutRedirectUri: appUrl,
    redirectUri: `${appUrl}/index.html`,
    silentRefreshRedirectUri: `${appUrl}/silent-refresh.html`,
    clientId: 'Opal2WebApp',
    scope: 'roles profile cxprofile openid cxDomainInternalApi',
    disablePKCE: false,
    showDebugInformation: true,
    sessionChecksEnabled: true,
    sessionCheckIntervall: 2000,
    skipIssuerCheck: true,
    ignoredPaths: [
      '/app/quiz-player',
      '/app/scorm-player',
      '/app/digital-content-player',
      '/app/video-annotation-player',
      '/app/community-metadata',
      '/app/assignment-player',
      '/app/calendar',
      '/app/form-standalone-player',
      '/app/assessment-player',
      '/app/standalone-survey'
    ]
  },
  idleConfig: {
    idleTimeoutInSecond: 1500,
    inActiveTimeoutInSecond: 300,
    userEvents: 'DOMMouseScroll keyup mousewheel mousedown touchstart touchmove scroll'
  },
  lastUpdateString: '12 June 2020',
  logoPath: 'assets/images/logos/opal.png'
};
