const appUrl: string = `${window.location.origin}/app`;

export const environment: IEnvironment = {
  envName: 'docker',
  production: false,
  manifest: 'assets/manifest.json',
  appUrl,
  apiUrl: '',

  cloudfrontApiUrl: 'http://localhost:5101/api',
  uploaderApiUrl: 'http://localhost:5102/api',
  contentApiUrl: 'http://localhost:5103/api',
  courseApiUrl: 'http://localhost:5104/api',
  formApiUrl: 'http://localhost:5105/api',
  learnerApiUrl: 'http://localhost:5106/api',
  taggingApiUrl: 'http://localhost:5107/api',
  brokenLinkApiUrl: 'http://localhost:5110/api',
  calendarApiUrl: 'http://localhost:5109/api',
  newsfeedApiUrl: 'http://localhost:5111/api',
  webinarApiUrl: 'http://localhost:5112/api',
  lnaFormApiUrl: 'http://localhost:5113/api',
  badgeApiUrl: 'http://localhost:5114/api',

  cslApiUrl: 'https://api.development.opal2.conexus.net/development-socialapp-opal-csl-api/api',
  cloudfrontUrl: 'https://dexzs7wx4278r.cloudfront.net',
  scormPlayerUrl: `https://dexzs7wx4278r.cloudfront.net/permanent/scorm-player/scorm-player.html`,
  userOnboardingUrl: `https://www.development.opal2.conexus.net/opal-account/opal-account/onboarding?returnUrl=${appUrl}/learner`,
  reportVulnerabilityUrl: 'https://www.tech.gov.sg/report_vulnerability',
  privacyPolicyUrl: 'https://idm.development.opal2.conexus.net/Home/PrivacyPolicy',
  termOfUse: 'https://idm.development.opal2.conexus.net/Home/TermsOfUse',
  competenceApiUrl: 'https://api.development.opal2.conexus.net/development-competence-opal-api',
  learningCatalogUrl: 'https://api.development.opal2.conexus.net/development-competence-opal-api-learningcatalog',
  reportUrl: 'https://www.development.opal2.conexus.net/report',
  AESSecretKey: '92AE31A79FEEB2A3',
  AESIv: 'H+MbQeThWmZq4t7w',
  ePortfolioUrl: 'https://www.development.opal2.conexus.net/eportfolio',
  pdplanUrl: 'https://www.development.opal2.conexus.net/pdplanner',
  cslUrl: 'https://www.development.opal2.conexus.net/csl',
  notificationUrl: 'https://www.development.opal2.conexus.net/opal-account/notifications/bell',
  broadcastMessageNotificationUrl: 'https://www.development.opal2.conexus.net/opal-account/notifications/alert',
  enableBroadcastMessage: false,
  enableBellNotification: false,
  authConfig: {
    strictDiscoveryDocumentValidation: false,
    requireHttps: false,
    responseType: 'code',
    issuer: 'https://idm.development.opal2.conexus.net',
    logoutUrl: 'https://idm.development.opal2.conexus.net/connect/endsession',
    profileUrl: 'https://www.development.opal2.conexus.net/opal-account/opal-account/profile',
    changePasswordUrl: 'https://idm.development.opal2.conexus.net/Manage/ChangePassword',
    sitesUrl: 'https://api.development.opal2.conexus.net/development-competence-opal-api-portal/sites',
    organizationUrl: 'https://api.development.opal2.conexus.net/development-competence-opal-api-organization',
    permissionUrl: 'https://api.development.opal2.conexus.net/development-competence-opal-api-portal/me/accessRights',
    // issuer: 'https://idm.systemtest.opal2.conexus.net',
    // logoutUrl: 'https://idm.systemtest.opal2.conexus.net/connect/endsession',
    // profileUrl: 'https://www.systemtest.opal2.conexus.net/opal-account/opal-account/profile',
    // changePasswordUrl: 'https://idm.systemtest.opal2.conexus.net/Manage/ChangePassword',
    // sitesUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api-portal/sites',
    // organizationUrl: 'https://apigw.systemtest.opal2.conexus.net/systemtest-competence-opal-api-organization',
    postLogoutRedirectUri: appUrl,
    redirectUri: `${appUrl}/index.html`,
    silentRefreshRedirectUri: `${appUrl}/silent-refresh.html`,
    clientId: 'Opal2WebApp',
    scope: 'roles profile cxprofile openid cxDomainInternalApi',
    disablePKCE: false,
    showDebugInformation: true,
    sessionChecksEnabled: true,
    sessionCheckIntervall: 2000,
    skipIssuerCheck: true,
    ignoredPaths: [
      '/quiz-player',
      '/scorm-player',
      '/digital-content-player',
      '/video-annotation-player',
      '/community-metadata',
      '/assignment-player',
      '/calendar',
      '/form-standalone-player',
      '/assessment-player',
      '/app/standalone-survey'
    ]
  },
  idleConfig: {
    idleTimeoutInSecond: 1500,
    inActiveTimeoutInSecond: 300,
    userEvents: 'DOMMouseScroll keyup mousewheel mousedown touchstart touchmove scroll'
  },
  lastUpdateString: '12 June 2020',
  logoPath: 'assets/images/logos/opal.png'
};
