version: '2.4'

services:
  webinar-video-converter-api:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT_NAME}
      - BuildVersion=${GO_PIPELINE_LABEL}
      - VIRTUAL_HOST=${ENVIRONMENT_NAME}-learnapp-${PROJECT_NAME}-api-webinar-video-converter.${DOMAIN_POSTFIX}
      - DeveloperExceptionEnabled={{ DeveloperExceptionEnabled }}
      - ConnectionStrings:Default=Data Source=${MSSQL_HOSTNAMES};Initial Catalog=${ENVIRONMENT_NAME}-webinar-record-management-${PROJECT_NAME}-db;User ID={{ mssql_username }};Password={{ mssql_password }}
      - RabbitMQOptions:HostNames=${RABBITMQ_HOSTNAMES}
      - RabbitMQOptions:UserName=${RABBITMQ_USERNAME}
      - RabbitMQOptions:Password=${RABBITMQ_PASSWORD}
      - RabbitMQOptions:SslEnabled=${RABBITMQ_SSL_ENABLED}
      - RabbitMQOptions:QueueName={{ RabbitMQOptions_QueueName }}
      - RabbitMQOptions:ExchangeName={{ RabbitMQOptions_ExchangeName }}
      - RabbitMQOptions:RetryCount={{ RabbitMQOptions_RetryCount }}
      - RabbitMQOptions:RetryPolicyInSeconds={{ RabbitMQOptions_RetryPolicyInSeconds }}
      - RabbitMQOptions:DefaultCommandExchange={{ RabbitMQOptions_DefaultCommandExchange }}
      - RabbitMQOptions:DefaultEventExchange={{ RabbitMQOptions_DefaultEventExchange }}
      - RabbitMQOptions:DefaultActivityExchange={{ RabbitMQOptions_DefaultActivityExchange }}
      - RabbitMQOptions:DefaultAuditLogExchange={{ RabbitMQOptions_DefaultAuditLogExchange }}
      - RabbitMQOptions:DefaultIntegrationExchange={{ RabbitMQOptions_DefaultIntegrationExchange }}
      - OpalAuthorityInternalUrl=${IDM_INTERNAL_URL}
      - OpalClientUrl={{ OpalClientUrl }}
      - AuthSettings:AuthorityUrl=${IDM_PUBLIC_URL}
      - Logging:LogLevel:Default=${APPLICATION_LOG_LEVEL}
      - Logging:LogLevel:Microsoft=${FRAMEWORK_LOG_LEVEL}
      - GetAccessRightsUrl={{GetAccessRightsUrl}}

      - RecordingConvertOptions:PlaybacksDir=/data/opal-webinar-efs/presentation/
      - RecordingConvertOptions:ConvertedVideoDir=/data/opal-webinar-efs/records/

      - PlaybackOptions:PlaybackUrl=http://${ENVIRONMENT_NAME}-webinar-playback.${DOMAIN_POSTFIX}/playback/presentation/2.3/

      - AWSOptions:AccessKey=${AWS_WEBINAR_ACCESS_KEY}
      - AWSOptions:SecretKey=${AWS_WEBINAR_SECRET_KEY}

      - AmazonS3Options:AccessKey=${S3_UPLOADER_API_KEY}
      - AmazonS3Options:SecretKey=${S3_UPLOADER_API_SECRET}
      - AmazonS3Options:BucketName=${ENVIRONMENT_NAME}-course-opal-content

      - ConverterTaskOptions:TaskDefinition=${WEBINAR_CONVERTER_TASK_DEFINITION_NAME}
      - ConverterTaskOptions:Cluster=${CLUSTER_NAME}
      - ConverterTaskOptions:ConverterContainerName=${WEBINAR_RECORDER_CONTAINER_NAME}
      - ConverterTaskOptions:SecurityGroupIds=${WEBINAR_RECORDER_SECURITY_GROUP_IDS}
      - ConverterTaskOptions:SubnetId=${WEBINAR_RECORDER_SUBNET_IDS}

{% if https_proxy is defined %}
      - HTTPS_PROXY={{ https_proxy }}
      - HTTP_PROXY={{ https_proxy }}
      - NO_PROXY=localhost,.opal
{% endif %}
    container_name: ${ENVIRONMENT_NAME}-webinar-video-converter-${PROJECT_NAME}-api
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    ports:
      - 0:80
    volumes:
      - /data/opal-webinar-efs/presentation:/data/opal-webinar-efs/presentation
      - /data/opal-webinar-efs/records:/data/opal-webinar-efs/records

networks:
  default:
    external:
      name: ${PROJECT_NAME}_default
